apiVersion: v2
name: todo-app-stack
description: A Helm chart for deploying the entire Todo application stack.
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: chatbot-backend
    version: "0.1.0"
    repository: "file://./chatbot-backend"
  - name: chatbot-frontend
    version: "0.1.0"
    repository: "file://./chatbot-frontend"
